name: 'Debug'
description: 'Generates a report with various statistics for a given CodeQL database.'
inputs:
  codeql-path:
    description: 'Path to the CodeQL executable or to a directory which contains at least one CodeQL distribution.'
    required: false
    default: "${{ runner.tool_cache }}/CodeQL"
  database-path:
    description: 'Path to the CodeQL database for which to generate a report.'
    required: false
    default: "${{ runner.temp }}/codeql_databases/"
  output-dir:
    description: 'Directory in which to output the debug report.'
    required: false
    default: 'codeql-debug-report'
  threads:
    description: 'Number of threads used for the analysis'
    required: false
    default: '1'
  ram:
    description: 'RAM in mega bytes used for the analysis'
    required: false
    default: '0'
runs:
  using: "composite"
  steps:
    - name: debug
      run: |
        "${{ github.action_path }}/../codeql-debug" \
        --codeql-path "${{ inputs.codeql-path }}" \
        --output-dir "${{ inputs.output-dir }}" \
        --threads "${{ inputs.threads }}" \
        --ram  "${{ inputs.ram }}" \
        --repo-url "${{ github.server_url }}/${{ github.repository }}" \
        "${{ inputs.database-path }}"
      shell: bash
