name: 'Debug'
description: 'Generates a report with various statistics for a given CodeQL database.'
inputs:
  codeql-path:
    description: 'Path to the CodeQL executable.'
    required: true
  database-path:
    description: 'Path to the CodeQL database for which to generate a report.'
    required: false
    default: "${{ runner.temp }}/codeql_databases/${{ matrix.language }}"
  output-dir:
    description: 'Directory in which to output the debug report.'
    required: false
    default: 'codeql-debug-report'
runs:
  using: "composite"
  steps:
    - name: debug
      run: |
        "${{ github.action_path }}/../codeql-debug" \
        --codeql-path "${{ inputs.codeql-path }}" \
        --output-dir "${{ inputs.output-dir }}" \
        "${{ inputs.database-path }}"
      shell: bash
